<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ELHI772V" failures="1" tests="8" name="PetTest" time="12.519" errors="0" timestamp="2025-02-24T16:25:12 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.449"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.157"/>
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.278"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.136"/>
  <testcase classname="api.test.StoreTest" name="testGetUserByName" time="1.139"/>
  <testcase classname="api.test.StoreTest" name="testPostUser" time="1.14"/>
  <testcase classname="api.test.StoreTest" name="testGetUserByOrderID" time="1.144"/>
  <testcase classname="api.test.StoreTest" name="deleteOrderById" time="1.151">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTest.deleteOrderById(StoreTest.java:91)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deleteOrderById -->
</testsuite> <!-- PetTest -->
