<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-ELHI772V" failures="3" tests="14" name="PetTest" time="20.099" errors="0" timestamp="2025-02-28T10:28:14 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="2.707"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="1.19">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.256"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.177"/>
  <testcase classname="api.test.StoreTest" name="testGetUserByName" time="1.14"/>
  <testcase classname="api.test.StoreTest" name="testPostUser" time="1.165"/>
  <testcase classname="api.test.StoreTest" name="testGetUserByOrderID" time="1.14">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.StoreTest.testGetUserByOrderID(StoreTest.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByOrderID -->
  <testcase classname="api.test.StoreTest" name="deleteOrderById" time="1.142"/>
  <testcase classname="api.test.PetsTest" name="testPostPets" time="1.153"/>
  <testcase classname="api.test.PetsTest" name="testPostPetsUpload" time="1.467"/>
  <testcase classname="api.test.PetsTest" name="testputPets" time="1.113"/>
  <testcase classname="api.test.PetsTest" name="getpetstatus" time="1.111"/>
  <testcase classname="api.test.PetsTest" name="testGetpetByPetID" time="1.154">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.PetsTest.testGetpetByPetID(PetsTest.java:118)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testGetpetByPetID -->
  <testcase classname="api.test.PetsTest" name="deleteOrderById" time="1.163"/>
</testsuite> <!-- PetTest -->
